Add check for -b option to ensure svn or git tree

diff --git a/portest b/portest
--- a/portest
+++ b/portest
@@ -144,32 +144,35 @@ fi
 # Check for commands #
 ${SVN} help >/dev/null 2>&1
 if [ "$?" -ne "0" ]; then
-        SVN_CHECK="NO"
+	SVN_CHECK="NO"
 fi
 ${GIT} help >/dev/null 2>&1
 if [ "$?" -ne "0" ]; then
-        GIT_CHECK="NO"
+	GIT_CHECK="NO"
 fi
 
 # Check PORTSDIR is an svn or git tree #
 cd ${PORTSDIR}
 if [ "${SVN_CHECK}" != "NO" ]; then
-        ${SVN} info >/dev/null 2>&1
-        if [ "$?" -eq "0" ]; then
-                REPO_TYPE="svn"
-                REPO="${SVN}"
-                REPO_STATUS="${SVN_STATUS_ARGS}"
-        fi
+	${SVN} info >/dev/null 2>&1
+	if [ "$?" -eq "0" ]; then
+		REPO_TYPE="svn"
+		REPO="${SVN}"
+		REPO_STATUS="${SVN_STATUS_ARGS}"
+	fi
 fi
 if [ "${GIT_CHECK}" != "NO" ]; then
-        ${GIT} branch >/dev/null 2>&1
-        if [ "$?" -eq "0" ]; then
-                REPO_TYPE="git"
-                REPO="${GIT}"
-                REPO_STATUS="${GIT_STATUS_ARGS}"
-        fi
+	${GIT} branch >/dev/null 2>&1
+	if [ "$?" -eq "0" ]; then
+		REPO_TYPE="git"
+		REPO="${GIT}"
+		REPO_STATUS="${GIT_STATUS_ARGS}"
+	fi
 fi
 
+if [ "${REPO_BUILD_LIST}" == "YES" ]; then
+	[ -z "${REPO_TYPE}" ] && echo "Port tree is not a svn or git tree, This is required with the -b option" && exit 1
+fi
 # Set patchfile path #
 cd "${PORTSDIR}"
 for file in "${@}"; do
